### ISSUE TITLE
Inconsistent mbox exports

### ISSUE THREAD

**Issue by jmgibson71** [StateArchivesOfNorthCarolina/tomes_tool#3]
Currently we are working with two versions of readpst. 

Windows Version:
`ReadPST / LibPST v0.6.45
Little Endian implementation being used.
GCC 3.4 : Oct 7 2016 13:02:30`

Linux Version:
======================
`ReadPST / LibPST v0.6.59
Little Endian implementation being used`

These produce inconsistent mbox representations.

The windows version seems to miss the RFC header "Status." It also apparently is fine with odd encodings in the headers of an email.

The Linux version seems to encode to base64 any non 8bit characters.  We noticed this in an email that had three 8bit characters in a subject line.

Continuing to investigate

**Comment by jmgibson71** [comment]
ZachAmbrose.xml	(linux version readpst output)  md5=d42227d1e1966240c72793b283371edf
ZachAmbrose (SentItems mbox linux version)         md5=20e067ef8f88af89590e50f7a67ce6ee
ZacAmbrose (SentItems mbox windows version)    md5=f76e42b1d725fa657238f9c41e4d10f5

**Comment by nitaro** [comment]
This no applies to TOMES Tool since it no longer does any PST to MBOX conversion.
So, closing.
