### ISSUE TITLE
Huge input error

### ISSUE THREAD

**Issue by jmgibson71** [StateArchivesOfNorthCarolina/tomes_tool#4]
> 2017-08-30 10:30:56,120 - __main__ - INFO - Tagging EAXS file: E:\RESOURCES\TEST_RESOURCES\tomes\data\eaxs\GovPerdue\eaxs_xml\GovPerdue.xml
> Traceback (most recent call last):
>   File "C:\Users\jgibson5\.IntelliJIdea2017.2\config\plugins\python\helpers\pydev\pydevd.py", line 1596, in <module>
>     globals = debugger.run(setup['file'], None, None, is_module)
>   File "C:\Users\jgibson5\.IntelliJIdea2017.2\config\plugins\python\helpers\pydev\pydevd.py", line 1023, in run
>     pydev_imports.execfile(file, globals, locals)  # execute the script
>   File "C:\Users\jgibson5\.IntelliJIdea2017.2\config\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
>     exec(compile(contents+"\n", file, 'exec'), glob, loc)
>   File "E:/RESOURCES/GIT/tomes_tool/main.py", line 146, in <module>
>     plac.call(main)
>   File "E:\pythonvenvs\python35\lib\site-packages\plac_core.py", line 328, in call
>     cmd, result = parser.consume(arglist)
>   File "E:\pythonvenvs\python35\lib\site-packages\plac_core.py", line 207, in consume
>     return cmd, self.func(*(args + varargs + extraopts), **kwargs)
>   File "E:/RESOURCES/GIT/tomes_tool/main.py", line 141, in main
>     tagger.eaxs_to_tagged(eaxs, output)
>   File "E:/RESOURCES/GIT/tomes_tool/main.py", line 116, in eaxs_to_tagged
>     tagged = self.e2t.write_tagged(eaxs_file, tagged_eaxs_file)
>   File "E:/RESOURCES/GIT/tomes_tool\lib\eaxs_to_tagged.py", line 223, in write_tagged
>     tagged_root = self.get_tagged(eaxs_file)
>   File "E:/RESOURCES/GIT/tomes_tool\lib\eaxs_to_tagged.py", line 185, in get_tagged
>     tagged = etree.parse(eaxs_file, parser).getroot()
>   File "src\lxml\lxml.etree.pyx", line 3427, in lxml.etree.parse (src\lxml\lxml.etree.c:81101)
>   File "src\lxml\parser.pxi", line 1811, in lxml.etree._parseDocument (src\lxml\lxml.etree.c:117832)
>   File "src\lxml\parser.pxi", line 1837, in lxml.etree._parseDocumentFromURL (src\lxml\lxml.etree.c:118179)
>   File "src\lxml\parser.pxi", line 1741, in lxml.etree._parseDocFromFile (src\lxml\lxml.etree.c:117091)
>   File "src\lxml\parser.pxi", line 1138, in lxml.etree._BaseParser._parseDocFromFile (src\lxml\lxml.etree.c:111637)
>   File "src\lxml\parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:105093)
>   File "src\lxml\parser.pxi", line 706, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:106801)
>   File "src\lxml\parser.pxi", line 635, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:105655)
>   File "file:/E:/RESOURCES/TEST_RESOURCES/tomes/data/eaxs/GovPerdue/eaxs_xml/GovPerdue.xml", line 3533510
> lxml.etree.XMLSyntaxError: internal error: Huge input lookup, line 3533510, column 9998937

Looks like very large files are breaking something.

**Comment by nitaro** [comment]
I think we've got this fixed now with our XML handling (fingers crossed).
There was also a memory leak in getting the GlobalId element value that's been fixed.
Closing this.
